version: "3.3"

services:
  app:
    container_name: my-profile-summary
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/health"]
      interval: 1m
      timeout: 10s
      retries: 3
